### ISSUE TITLE
not supported outside strict mode

### ISSUE THREAD

**Issue by aycgit** [haganbmj/obs-websocket-js#64]
### Is this a request for a new *feature* or a *bug* report?
bug
### Description:
importing obswebsocket throws the error:

```
C:\Users\werel\node_modules\obs-websocket-js\lib\OBSWebSocket.js:6
let requestCounter = 0;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\werel\node_modules\obs-websocket-js\index.js
:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

### Steps to Reproduce the Issue (if applicable):
-

### Versions Used (if applicable):
all newest as of 14th august 2017

### Extra Information / Code Samples / etc:
None

**Comment by aycgit** [comment]
oops this was a obswebsocket error

**Comment by haganbmj** [comment]
Hm, so you're using node, but it gets past the const imports and complains on let? 
Double check your node version? 
I'll go back in and add a 'use strict' declaration just in case.

**Comment by aycgit** [comment]
yes, there was another error when i added use strict but i need to look into that

**Comment by haganbmj** [comment]
Updated the project and everything should be in order. Made sure to run unit tests with Node v4.8.4 to ensure compatibility.
Try updating to obs-websocket-js `v0.8.0` and let me know if you run into any issues.

Let me know what version of node you're using if that doesn't work (`node -v`), it's possible you're using something even older.
