### ISSUE TITLE
obs.connect SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Bigmacbook** [haganbmj/obs-websocket-js#69]
My Code:

`
const OBSWebSocket = require('obs-websocket-js');
const obs = new OBSWebSocket();
obs.connect({ address: 'localhost:4444'});
`
Error:

C:\Users\compt\Desktop\OBS\node_modules\obs-websocket-js\lib\Socket.js:36
  async connect(args = {}, callback) {
           ^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\compt\Desktop\OBS\node_modules\obs-websocket-js\lib\OBSWebSocket.js:1:78)
    at Module._compile (module.js:541:32)

**Comment by haganbmj** [comment]
`async` is only available in newer versions of node. 
I started working on transpiling last night so that this can support older node versions which should take care of that.

I'll post an update when I have that working.

**Comment by Bigmacbook** [comment]
I'm not using async. thats the problem

**Comment by haganbmj** [comment]
Looks like you deleted the post, but yeah - you're not using async; I am and your node version doesn't like it.

**Comment by haganbmj** [comment]
Updated the project and everything should be in order. Made sure to run unit tests with Node v4.8.4 to ensure compatibility.
Try updating to obs-websocket-js `v0.8.0` and let me know if you run into any issues.

**Comment by Kaliph** [comment]
Thankyou I will try and let you know. BR
