### ISSUE TITLE
ConnectionClosed Event is not working with v1.0.0

### ISSUE THREAD

**Issue by Kaliph** [haganbmj/obs-websocket-js#93]
ConnectionClosed Event is not working with v1.0.0

  - obs-websocket-js version: 1.0.0
  - obs-websocket plugin version: 4.2.0
  - obs-studio version: 20.1.3
  - node version: 8.7.0

Error message

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at TCP.onread (net.js:608:25)

**Comment by haganbmj** [comment]
That'd be the host server dropping the connection, I'll take a look and see if there's a reason that doesn't trigger a connection closed event.

**Comment by haganbmj** [comment]
Can't seem to get a good way to duplicate this.
If you're running in node you can add a catch for uncaughtExceptions to at least prevent a crash.
I'll check around and see if there's some additional ways to catch socket exceptions that I might be missing.

```js
process.on('uncaughtException', (err) => {
    console.error(err);
});
```

**Comment by spesvictus** [comment]
Have you tried to do a force quit/end task in task manager on obs to duplicate?

**Comment by Kaliph** [comment]
Hello Sorry for my late reply. 

with Version obs-websocket-js 1.1.0 

I get following Error when closing the connected OBS Studio. How can I help you to debug this better.
I am using Windows 7. 

`    at _errnoException (util.js:1021:11)
    at TCP.onread (net.js:608:25)
C:\project\digital-ocean\node_modules\has-binary2\index.js:28
function hasBinary (obj) {

RangeError: Maximum call stack size exceeded
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:28:20)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
[nodemon] app crashed - waiting for file changes before starting...`

with obs-websocket-js 0.9.0 I dont have those problems. But I also get an unhandled Promise rejection warning when I have not started OBS Studio and want to connect.

> (node:2124) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:2222
(node:2124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kaliph** [comment]
with obswebsocket-js 1.0.0 and obs websocket plugin 4.3.0 I get 

>     at _errnoException (util.js:1021:11)
    at TCP.onread (net.js:608:25)
buffer.js:392
Buffer.isBuffer = function isBuffer(b) {
                                   ^

RangeError: Maximum call stack size exceeded
    at Function.isBuffer (buffer.js:392:36)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:42:87)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)
    at hasBinary (C:\project\digital-ocean\node_modules\has-binary2\index.js:56:59)

**Comment by haganbmj** [comment]
If there's a difference between 0.9 and 1.0.0 then these two commits apply
- https://github.com/haganbmj/obs-websocket-js/commit/47ac5e60cdfc931bb07f04b64b9829201970065d
- https://github.com/haganbmj/obs-websocket-js/commit/6cf99e2801a610e9282da22ab2c3bacb016ceffc

If it's between 1.0.0 and 1.1.0 then the only changes were with the dependencies used. 
- https://github.com/haganbmj/obs-websocket-js/commit/fb829725b44d64c44b0b701ce91cbff51aa6ba3c

If you don't already have the logging environment variable set, that'd be helpful to see.

```sh
DEBUG=obs-websocket-js:*
```

**Comment by Kaliph** [comment]
It is between 0.9.0 and 1.0.0. with 0.9.0 the disconnect event is fired properly.

**Comment by Kaliph** [comment]
Where can I set Debug?

**Comment by haganbmj** [comment]
Alright, I was able to trigger this in a test case.
I was misunderstanding how EventEmitter treated emitting `error`. Apparently that can get you an Uncaught Exception.
So when this was written it essentially enforced having an `error` handler, something that I thought would continue to be an optional requirement.
https://github.com/haganbmj/obs-websocket-js/commit/6cf99e2801a610e9282da22ab2c3bacb016ceffc#diff-ce3eb7273f12ecefb326730c4fd17e9aR65

So, ensure that you have an error handler at least written. It doesn't have to actually do anything.

```js
obs.on('error', err => {
    console.error(err);
});
```

I'll see if there's some way I can look through this and make it more evident or allow it to be optional.

**Comment by Kaliph** [comment]
I have this error handler set. But it seems it doesn´t handle this error. I get the above error when closing OBS Studio. which should in normal case trigger a ConnectionClosed event... But it doesn´t in 1.0.0 and higher...

**Comment by haganbmj** [comment]
Sorry for not following up on this, stumbled upon this issue https://github.com/websockets/ws/issues/1256 and it started to make more sense as it would've been the transitive `ws` dependency (as of version `3.3.3`) getting more strict about error handling.
These errors don't happen browser-side because that uses the browser's implementation of `WebSocket` instead.

The proposed solution from `ws` is, as before, add an error handler. I'm going to try adding one within the wrapped socket handler in this project.

At the end of that issue discussion it appears that these changes are being reverted though and errors will be handled more similarly to how they were before `3.3.3` in `5.0.0`.

**Comment by Kaliph** [comment]
No problem. I have just tested the ConnectionClosed not fired problem with your new Version 1.2.0.
With this version the problem is gone. In v.1.1.0 It was still present. Thanks for fixing this bug
